export const links=[
    {
        id:1,
        title:"Home",
        url:"/"
    },
    {
        id:2,
        title:"Portfolio",
        url:"/portfolio"
    },
    {
        id:3,
        title:"Blog",
        url:"/blog"
    },
    {
        id:4,
        title:"About",
        url:"/about"
    },
    {
        id:5,
        title:"Contact",
        url:"/contact"
    },
    {
        id:6,
        title:"Dashboard",
        url:"/dashboard"
    },
]

export const footerImages=[
    {
        id:1,
        url:"/1.png",
        title:"facebook"
    }
    ,{
        id:2,
        url:"/2.png",
        title:"instagram"
    },
    {
        id:3,
        url:"/3.png",
        title:"twitter"
    },
    {
        id:4,
        url:"/4.png",
        title:"youtube"
    }
]